# Generated by Django 4.1.5 on 2023-01-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('logo', models.CharField(default='photo of person', max_length=25)),
                ('pan_no', models.BigIntegerField()),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('pan_no', models.BigIntegerField()),
                ('image', models.CharField(default='photo of person', max_length=25)),
                ('designation', models.CharField(choices=[('Employee', 'employee'), ('Manager', 'manager'), ('Human Resource Manager', 'hr')], max_length=50)),
                ('joined_date', models.CharField(default='Date', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('reason', models.TextField()),
                ('date', models.CharField(default='Date', max_length=25)),
                ('for_days', models.IntegerField()),
                ('is_approved', models.BooleanField()),
                ('is_declined', models.BooleanField()),
                ('is_pending', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('image', models.CharField(default='photo of person', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LogStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_login', models.CharField(default='time here', max_length=25)),
                ('time_of_logout', models.CharField(default='time here', max_length=25)),
                ('leave_days', models.IntegerField()),
                ('leave_count', models.IntegerField()),
                ('is_late', models.BooleanField()),
                ('is_attendance_low', models.BooleanField()),
                ('is_late_for_thrice', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.FloatField()),
                ('tax_percent', models.FloatField()),
                ('tax_amount', models.FloatField()),
                ('gross_salary', models.FloatField()),
                ('overtime', models.FloatField()),
                ('allowance', models.FloatField()),
                ('Bonus', models.FloatField()),
                ('medical_claim', models.FloatField()),
                ('net_salary', models.FloatField()),
            ],
        ),
    ]
