# Generated by Django 4.1.4 on 2023-01-16 02:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='for_days',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_declined',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_pending',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='title',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='Bonus',
        ),
        migrations.AddField(
            model_name='designation',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='issue',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending', 'Pending')], default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='logstat',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.AddField(
            model_name='logstat',
            name='is_login',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='payroll',
            name='designation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.designation'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='uploads/logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='uploads/employee/employee_id'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logstat',
            name='time_of_login',
            field=models.CharField(default="haven't Logged In", max_length=25),
        ),
        migrations.AlterField(
            model_name='logstat',
            name='time_of_logout',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='allowance',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='medical_claim',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='overtime',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('reason', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('for_days', models.IntegerField()),
                ('apply_for', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.issuetype')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='issue',
            field=models.ManyToManyField(default=None, to='api.application'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
